databases:
  - name: "钱包服务本地数据库"
    type: "mysql"
    host: "192.168.31.227"
    port: 3306
    username: "wallet_service"
    password: "dbXhkMWJkFrndfCX"
    database: "wallet_service"

  - name: "网关本地数据库"
    type: "mysql"
    host: "192.168.31.227"
    port: 3306
    username: "apinto-gateway"
    password: "3SsPxpK6a653n4Sb"
    database: "apinto-gateway"
   
  - name: "PostgreSQL本地数据库"
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database: "test"
    sslmode: "disable"
    
  - name: "MySQL生产数据库"
    type: "mysql"
    host: "prod.mysql.com"
    port: 3306
    username: "user"
    password: "prod_password"
    database: "production"

# 输出配置
output:
  directory: "./output"  # 输出目录
  filename_format: "{database}_tables_ddl.sql"  # 汇总文件名格式，{database}会被替换
